/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarnaRouteImport } from './routes/warna'
import { Route as TipografiLogoRouteImport } from './routes/tipografi-logo'
import { Route as TipografiRouteImport } from './routes/tipografi'
import { Route as SignatureLogoRouteImport } from './routes/signature-logo'
import { Route as SegelAkademikRouteImport } from './routes/segel-akademik'
import { Route as PusatUnduhanRouteImport } from './routes/pusat-unduhan'
import { Route as LambangFakultasRouteImport } from './routes/lambang-fakultas'
import { Route as IndexRouteImport } from './routes/index'

const WarnaRoute = WarnaRouteImport.update({
  id: '/warna',
  path: '/warna',
  getParentRoute: () => rootRouteImport,
} as any)
const TipografiLogoRoute = TipografiLogoRouteImport.update({
  id: '/tipografi-logo',
  path: '/tipografi-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const TipografiRoute = TipografiRouteImport.update({
  id: '/tipografi',
  path: '/tipografi',
  getParentRoute: () => rootRouteImport,
} as any)
const SignatureLogoRoute = SignatureLogoRouteImport.update({
  id: '/signature-logo',
  path: '/signature-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const SegelAkademikRoute = SegelAkademikRouteImport.update({
  id: '/segel-akademik',
  path: '/segel-akademik',
  getParentRoute: () => rootRouteImport,
} as any)
const PusatUnduhanRoute = PusatUnduhanRouteImport.update({
  id: '/pusat-unduhan',
  path: '/pusat-unduhan',
  getParentRoute: () => rootRouteImport,
} as any)
const LambangFakultasRoute = LambangFakultasRouteImport.update({
  id: '/lambang-fakultas',
  path: '/lambang-fakultas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lambang-fakultas': typeof LambangFakultasRoute
  '/pusat-unduhan': typeof PusatUnduhanRoute
  '/segel-akademik': typeof SegelAkademikRoute
  '/signature-logo': typeof SignatureLogoRoute
  '/tipografi': typeof TipografiRoute
  '/tipografi-logo': typeof TipografiLogoRoute
  '/warna': typeof WarnaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lambang-fakultas': typeof LambangFakultasRoute
  '/pusat-unduhan': typeof PusatUnduhanRoute
  '/segel-akademik': typeof SegelAkademikRoute
  '/signature-logo': typeof SignatureLogoRoute
  '/tipografi': typeof TipografiRoute
  '/tipografi-logo': typeof TipografiLogoRoute
  '/warna': typeof WarnaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lambang-fakultas': typeof LambangFakultasRoute
  '/pusat-unduhan': typeof PusatUnduhanRoute
  '/segel-akademik': typeof SegelAkademikRoute
  '/signature-logo': typeof SignatureLogoRoute
  '/tipografi': typeof TipografiRoute
  '/tipografi-logo': typeof TipografiLogoRoute
  '/warna': typeof WarnaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lambang-fakultas'
    | '/pusat-unduhan'
    | '/segel-akademik'
    | '/signature-logo'
    | '/tipografi'
    | '/tipografi-logo'
    | '/warna'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lambang-fakultas'
    | '/pusat-unduhan'
    | '/segel-akademik'
    | '/signature-logo'
    | '/tipografi'
    | '/tipografi-logo'
    | '/warna'
  id:
    | '__root__'
    | '/'
    | '/lambang-fakultas'
    | '/pusat-unduhan'
    | '/segel-akademik'
    | '/signature-logo'
    | '/tipografi'
    | '/tipografi-logo'
    | '/warna'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LambangFakultasRoute: typeof LambangFakultasRoute
  PusatUnduhanRoute: typeof PusatUnduhanRoute
  SegelAkademikRoute: typeof SegelAkademikRoute
  SignatureLogoRoute: typeof SignatureLogoRoute
  TipografiRoute: typeof TipografiRoute
  TipografiLogoRoute: typeof TipografiLogoRoute
  WarnaRoute: typeof WarnaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warna': {
      id: '/warna'
      path: '/warna'
      fullPath: '/warna'
      preLoaderRoute: typeof WarnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipografi-logo': {
      id: '/tipografi-logo'
      path: '/tipografi-logo'
      fullPath: '/tipografi-logo'
      preLoaderRoute: typeof TipografiLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipografi': {
      id: '/tipografi'
      path: '/tipografi'
      fullPath: '/tipografi'
      preLoaderRoute: typeof TipografiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signature-logo': {
      id: '/signature-logo'
      path: '/signature-logo'
      fullPath: '/signature-logo'
      preLoaderRoute: typeof SignatureLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segel-akademik': {
      id: '/segel-akademik'
      path: '/segel-akademik'
      fullPath: '/segel-akademik'
      preLoaderRoute: typeof SegelAkademikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pusat-unduhan': {
      id: '/pusat-unduhan'
      path: '/pusat-unduhan'
      fullPath: '/pusat-unduhan'
      preLoaderRoute: typeof PusatUnduhanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lambang-fakultas': {
      id: '/lambang-fakultas'
      path: '/lambang-fakultas'
      fullPath: '/lambang-fakultas'
      preLoaderRoute: typeof LambangFakultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LambangFakultasRoute: LambangFakultasRoute,
  PusatUnduhanRoute: PusatUnduhanRoute,
  SegelAkademikRoute: SegelAkademikRoute,
  SignatureLogoRoute: SignatureLogoRoute,
  TipografiRoute: TipografiRoute,
  TipografiLogoRoute: TipografiLogoRoute,
  WarnaRoute: WarnaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
